/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Forms;
import static Tools.Tools.Message;
import entities.Note;
import java.awt.Color;
import java.awt.Font;
import java.awt.HeadlessException;
import java.awt.print.PrinterException;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.text.MessageFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Scanner;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import jxl.Sheet;
import jxl.Workbook;
import jxl.read.biff.BiffException;
import static org.apache.poi.hssf.usermodel.HeaderFooter.tab;

/**
 *
 * @author Abdelatif Hamdi
 */
public class notesForm extends javax.swing.JFrame {

    /**
     * Creates new form notesForm
     */
    public notesForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jMyCombo1 = new controls.JMyCombo();
        jLabel5 = new javax.swing.JLabel();
        jMyBottom3 = new controls.JMyBottom();
        jMyBottom1 = new controls.JMyBottom();
        jMyBottom4 = new controls.JMyBottom();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabNotes = new javax.swing.JTable();
        txtRech = new controls.JTextBox(15,Color.BLUE);
        jLabel1 = new javax.swing.JLabel();
        jMyBottom5 = new controls.JMyBottom();

        jLabel6.setFont(new java.awt.Font("Traditional Arabic", 1, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(70, 130, 180));
        jLabel6.setText("الإعدادات");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("المواد :");

        jMyCombo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMyCombo1ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Traditional Arabic", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(70, 130, 180));
        jLabel5.setText("حجز النقاط");

        jMyBottom3.setForeground(new java.awt.Color(0, 0, 0));
        jMyBottom3.setText("تأكيد المعدلات مع حساب النقاط");
        jMyBottom3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMyBottom3ActionPerformed(evt);
            }
        });

        jMyBottom1.setForeground(new java.awt.Color(0, 0, 0));
        jMyBottom1.setText("طباعة النتائج الاولية");
        jMyBottom1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMyBottom1ActionPerformed(evt);
            }
        });

        jMyBottom4.setForeground(new java.awt.Color(0, 0, 0));
        jMyBottom4.setText("رفع ملف التشفير F1");
        jMyBottom4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMyBottom4ActionPerformed(evt);
            }
        });

        tabNotes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "المادة الثانية", "المادة الاولى", "الرمز السري"
            }
        ));
        tabNotes.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane1.setViewportView(tabNotes);

        txtRech.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("البحث بالرمز السري : ");

        jMyBottom5.setForeground(new java.awt.Color(0, 0, 0));
        jMyBottom5.setText("البحث");
        jMyBottom5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMyBottom5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 736, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jMyBottom5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtRech, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel1)
                        .addGap(159, 159, 159))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(321, 321, 321)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jMyBottom4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(163, 163, 163)
                        .addComponent(jMyBottom3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(95, 95, 95)
                        .addComponent(jMyBottom1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jMyBottom1, jMyBottom3});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(jMyBottom4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtRech, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jMyBottom5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jMyBottom1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jMyBottom3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMyCombo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMyCombo1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMyCombo1ActionPerformed
private String[] getCells(String enrg){
String cells[]=new String[18];
int j=0;
for(int k=0;k<18;k++){
cells[k]="";
while(j<enrg.length()){
if (enrg.charAt(j)==';'){
j++; break;
} else{
cells[k]+=enrg.charAt(j); j++;
}}}
return cells;}
    private void jMyBottom4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMyBottom4ActionPerformed
try{
    JFileChooser jfc = new JFileChooser();
int test = jfc.showOpenDialog(null);
if(test == JFileChooser.APPROVE_OPTION)
{
File exf = jfc.getSelectedFile();
          
if (".csv".equals(Tools.Tools.getFileExtension(exf))){
try {
        Scanner inputStream = new Scanner(exf);
        DefaultTableModel model = (DefaultTableModel)tabNotes.getModel();
        model.setRowCount(0);
        while (inputStream.hasNext()){
            String data = inputStream.nextLine();
            String cells = data;
        Object  row[] = new Object[3];   
      row[0]="";
      row[1]="";
      row[2]=(cells);
      model.addRow(row);

        }
        inputStream.close();
        
        } catch (FileNotFoundException e) {
        // TODO Auto-generated catch block
        e.printStackTrace();
    }
    
}else if (".xls".equals(Tools.Tools.getFileExtension(exf))){
   Workbook wb = Workbook.getWorkbook(exf);
    Sheet s = wb.getSheet(0);
    int Rows = s.getRows(); 
    DefaultTableModel model = (DefaultTableModel)tabNotes.getModel();

    model.setRowCount(0);
        

for (int n = 0 ;n<Rows;n++){
        Object  row[] = new Object[3];
      
      row[0]="";
      row[1]="";
      row[2]=(s.getCell(0, n).getContents());
      model.addRow(row);
}}
Tools.Tools.Message("Le fichier excle est importé avec succès");
}}
         catch (HeadlessException | IOException | IndexOutOfBoundsException | BiffException ex){
            Tools.Tools.Message(ex);}}
     
/*
}    }                                       }//GEN-LAST:event_jMyBottom4ActionPerformed
*/
    private void jMyBottom1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMyBottom1ActionPerformed
try {
            MessageFormat header = new MessageFormat("النتائج الأولية");
            MessageFormat footer = new MessageFormat("Page - {0}");
            tabNotes.print(JTable.PrintMode.FIT_WIDTH, header, footer);
        } catch (PrinterException ex) {
         Message(ex.getMessage());
        }    }//GEN-LAST:event_jMyBottom1ActionPerformed
int decode(String code)
	{String alphabets = "AZERTYUIOPQSDFGHJKLMWXCVBN";
		int n = code.length() - 1;

		int numero = 0;

		for (int i = n; i > 0; i = i-2)
		{
			char alphabet = code.charAt(i-1);
			int index = alphabets.indexOf(alphabet);
			int divider = charToInt(code.charAt(i));

			int portion = divider * 26 + index;

			numero = numero*100 + portion;
		}

		return numero;
	}

	int charToInt(char symbol)
	{
		return symbol % 48;
	}
    private void jMyBottom3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMyBottom3ActionPerformed
DefaultTableModel model = (DefaultTableModel)tabNotes.getModel();
    
        

for (int n = 0 ;n<model.getRowCount();n++){
          Object row[] = new Object[3];
      for (int i =0 ;i<3;i++){
          
     row[i]=( model.getValueAt(n, i));
      }
      int id = decode((String) row[2]);
      double note1 = (Double.parseDouble((String) row[1]));
      double note2 = (Double.parseDouble((String) row[0]));
      note.saisirNote(id,1,note1);
      note.saisirNote(id,2,note2);
      
 
}
        
    }//GEN-LAST:event_jMyBottom3ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
tabNotes.getTableHeader().setReorderingAllowed(false);
        tabNotes.getTableHeader().setFont(new Font("Tahoma",Font.BOLD,13));
tabNotes.getTableHeader().setOpaque(false);
tabNotes.getTableHeader().setBackground(new Color(32, 136, 203));    }//GEN-LAST:event_formWindowOpened

    private void jMyBottom5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMyBottom5ActionPerformed
DefaultTableModel model = (DefaultTableModel)tabNotes.getModel();

for (int n = 0 ;n<model.getRowCount();n++){
      
     if ((model.getValueAt(n, 2)).equals((txtRech.getText()))){
        tabNotes.setRowSelectionInterval(n, n);
        break;
     }}
      
        
    }//GEN-LAST:event_jMyBottom5ActionPerformed
Note note = new Note();
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(notesForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(notesForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(notesForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(notesForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new notesForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private controls.JMyBottom jMyBottom1;
    private controls.JMyBottom jMyBottom3;
    private controls.JMyBottom jMyBottom4;
    private controls.JMyBottom jMyBottom5;
    private controls.JMyCombo jMyCombo1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabNotes;
    private javax.swing.JTextField txtRech;
    // End of variables declaration//GEN-END:variables
}
